version: "3"
services:
  php:
    build:
      context: ./docker/php
      args:
        TIME_ZONE: "Europe/Berlin"
    environment:
      # See https://xdebug.org/docs/all_settings#mode
      XDEBUG_MODE: "${XDEBUG_MODE:-off}"
    ports:
      - 9000:9000
    volumes:
      - ./:/var/www/html/
    networks:
      - kirby
  httpd:
    build:
      context: "./docker/httpd/"
    depends_on:
      - php
    ports:
      - 8000:80
    volumes:
      - ./:/var/www/html/:ro
    networks:
      - kirby
  mailhog:
    image: mailhog/mailhog:latest
    ports:
      - 1025:1025
      - 8025:8025
    networks:
      - kirby
networks:
  kirby:
    driver: bridge
