title: Site

tabs:
  content:
    icon: dashboard
    columns:
      - width: 1/2
        sections:
          articles: sections/articles
      - width: 1/2
        sections:
          singles:
            type: pages
            create: false
            sortable: false
            sortBy: "title desc"
            empty: Please contact admin
            templates:
              - home
              - error
              - articles
          pages: sections/pages

  globals: sections/globals

  media:
    icon: folder
    label: Media
    sections:
      media: sections/media

  seo:
    label: Default SEO
    extends: seo/site
