title: Site

tabs:
  content:
    icon: dashboard
    columns:
      - width: 2/3
        sections:
          pages:
            label: Pages
            type: pages
            search: true
            create: default
            templates: default
            limit: 25
      - width: 1/3
        sections:
          singles:
            type: pages
            create: false
            sortable: false
            sortBy: "title desc"
            empty: Please contact admin
            templates:
              - home
              - error
          articles:
            extends: sections/articles
            label: Latest Articles
            create: article
            status: all
            templates: article
            sortable: false
            max: 20
  navigation:
    icon: folder-structure
    fields:
      navigation:
        label: Navigation
        type: navigation
        levels: 3
        width: 2/3

  globals:
    icon: globe
    columns:
      - width: 1/2
        fields:
          copyright:
            type: text
            placeholder: @2023
          socialMedia:
            label: Social Media
            type: structure
            fields:
              service:
                type: select
                default: facebook
                required: true
                options:
                  facebook: Facebook
                  instagram: Instagram
                  linkedin: LinkedIn
                  tiktok: TikTok
                  twitter: Twitter
              url:
                label: URL
                type: url
  seotab:
    label: Default SEO
    extends: seo
