title: Site

tabs:
  content:
    columns:
      - width: 1/2
        sections:
          singles:
            type: pages
            create: default
            templates:
              - home
              - error
      - width: 1/2
        sections:

  seotab: seo
